#include <iostream>
#include "Interfaz.h"

using namespace std;


void Interfaz::imprimirMensaje(char* mensaje)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C2D begin
{
    cout << mensaje << endl;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Interfaz::imprimirHilera(char* mensaje)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C2D begin
{
    cout << mensaje;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Interfaz::imprimirNumero(int n)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C2D begin
{
    cout << n;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Interfaz::imprimirCambioLinea()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C2D begin
{
    cout << endl;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C2D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Interfaz::pedirEnteroRestriccion(char* mensaje, int min, int max)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C36 begin
{
	int *n = new int;
	cout << mensaje;
	cin >> *n;
	if(*n < min || *n > max)
		do{
			cout << "El numero que digitastes no es correcto. Por favor intenta de nuevo: ";
			cin >> *n;
		}while(*n < min || *n > min);
    return *n;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C36 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char* Interfaz::pedirHilera(char* mensaje, int tamano)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C38 begin
{
	char *msj = new char[tamano];
	cout << mensaje;
	cin >> msj;
    return msj;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C38 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char Interfaz::pedirCaracter(char* mensaje)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C38 begin
{
	char c = 'a';
	cout << mensaje;
	cin >> c;
    return c;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C38 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
