#include <stdlib.h>
#include <string.h>
#include "Secuencia.h"




int Secuencia::generarSecuencia(int largo)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C21 begin
{
	*largoSecuencia = largo;
	secuencia = new char[largo];
	for(int i = 0; i < largo; i++)
		secuencia[i] = simbolos[(rand() % 5)];
    return 0;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C21 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Secuencia::Secuencia()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C73 begin
{
	largoSecuencia = new int;
	simbolos = "@#$%&";
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C73 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Secuencia::~Secuencia()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C79 begin
{
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000C79 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Secuencia::evaluarRespuesta(char* respuesta)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000CC2 begin
{
	int c = 0;
	for(int i = 0; i < strlen(secuencia); i++)
		if(respuesta[i] == secuencia[i])
			c++; //lol
	return c;
    return 0;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000CC2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Secuencia::getLargoSecuencia()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000CC2 begin
{
    return *largoSecuencia;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000CC2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

char* Secuencia::getSimbolos()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000CC2 begin
{
    return simbolos;
}
// section 127-0-1-1--140c5f42:144c839e4da:-8000:0000000000000CC2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
